services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contact_manager_php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    networks:
      - contact_network
    restart: unless-stopped

  mariadb:
    image: mariadb:10.11
    container_name: contact_manager_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contact
      MYSQL_USER: contact
      MYSQL_PASSWORD: "12?34?56?Aa"
    ports:
      - "3307:3306"
    volumes:
      - contact_data:/var/lib/mysql
    networks:
      - contact_network

networks:
  contact_network:

volumes:
  contact_data:
